version: "3"
services:
  cherish-backend:
    container_name: tingle-backend
    build: ./back/tingle
    image: tingle_back_image:0.0
    ports:
      - "8080:8080"
    volumes:
      - /home/ubuntu/back:/home/ubuntu/back
    networks:
      - backend_frontend

  cherish-frontend:
    container_name: tingle-frontend
    build: ./front/tingle
    image: tingle_front_image:0.0
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
      - /home/ubuntu/nginx/sites:/etc/nginx/conf.d
      - /home/ubuntu/nginx/sites/sites-enabled:/etc/nginx/sites-enabled
    networks:
      - backend_frontend

networks:
  backend_frontend:
    driver: bridge